# Generated by Django 2.0.4 on 2018-06-19 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=256)),
                ('state', models.CharField(max_length=256)),
                ('start_date', models.CharField(max_length=256)),
                ('start_time', models.CharField(max_length=256)),
                ('end_date', models.CharField(max_length=100)),
                ('end_time', models.CharField(max_length=256)),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('description', models.TextField()),
                ('code', models.CharField(max_length=256)),
            ],
        ),
    ]
