# Generated by Django 2.0.4 on 2018-07-20 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180630_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventprofile',
            name='account_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
